name: Preprocess AQI Data Hourly

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  preprocess-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn "hopsworks[python]" pyarrow

      - name: Run preprocessing script
        run: python 10Pearls2/EDA_and_Preprocessing/Data_Preprocessing+Feature_Engineering.py
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}

      - name: Commit and push updated CSV to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add preprocessed_aqi_data.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Update preprocessed AQI data from GitHub Actions"
          git push
